$ANSIBLE_VAULT;1.1;AES256
66663639376463363133306634313661383432613234636465626163653563643561386463633733
6630616633663038346635323164363763326236643466360a613762363933653931353539303837
35373166333336616261306332353663656634333731633732636432383731616361363663326361
6661626339623233350a393066333235383831346332373961336235336636306665313334643331
35633837326264656365316335366336323165373433373233333865326435346161353833373063
31373561666136373339613631333834346164306163323538633636656430346532343465303565
31336336393766346633336264376366633937633862363130383330323639613565333730643530
37626631373234376665396639336433393330366631616261653164306331633337623235646236
62613036363034376635316438326234656664313762356366343236376564383139
